### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by niuqun** [twtygqyy/pytorch-SRResNet#13]
Dear all, I encounter this problem at the start of my training. Could anyone help? The error message is as follows: 

user@userVM:~/\u4e0b\u8f7d/SRResNet$ python main_srresnet.py --cuda --vgg_loss --gpus 0
/home/user/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Namespace(batchSize=16, cuda=True, gpus='0', lr=0.0001, nEpochs=500, pretrained='', resume='', start_epoch=1, step=200, threads=0, vgg_loss=True)
=> use gpu id: '0'
Random Seed:  3780
===> Loading datasets
===> Loading VGG model
===> Building model
/home/user/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
===> Setting GPU
===> Setting Optimizer
===> Training
Epoch=1, lr=0.0001
Traceback (most recent call last):
  File "main_srresnet.py", line 166, in <module>
    main()
  File "main_srresnet.py", line 104, in main
    train(training_data_loader, optimizer, model, criterion, epoch)
  File "main_srresnet.py", line 122, in train
    for iteration, batch in enumerate(training_data_loader, 1):
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 313, in __next__
    indices = next(self.sample_iter)  # may raise StopIteration
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 138, in __iter__
    for idx in self.sampler:
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 51, in __iter__
    return iter(torch.randperm(len(self.data_source)).tolist())
  File "/home/user/\u4e0b\u8f7d/SRResNet/dataset.py", line 16, in __len__
    return self.data.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

The generate_train_srresnet.m script is extremely slow. To speed up, I fix downsizes to 0.5 and generate a srresnet_x4.h5 (2.3GB). I checked the subim_input and subim_input, which seem valid. But I just do not understand why this happens. Could anyone help me with this? Thanks.

**Comment by niuqun** [comment]
Sorry, my bad. I forgot to put the h5 file in the right folder.
